wordpress:
  ## @param wordpressUsername WordPress username
  ##
  wordpressUsername: admin
  ## @param wordpressPassword WordPress user password
  ## Defaults to a random 10-character alphanumeric string if not set
  wordpressPassword: "admin123+"

  wordpressEmail: oliver.wagner@noventi.de
  ## @param wordpressFirstName WordPress user first name
  ##
  wordpressFirstName: Oliver
  ## @param wordpressLastName WordPress user last name
  ##
  wordpressLastName: Wagner
  ## @param wordpressBlogName Blog name



  ## SMTP mail delivery configuration
  ## ref: https://github.com/bitnami/bitnami-docker-wordpress/#smtp-configuration
  ## @param smtpHost SMTP server host
  ## @param smtpPort SMTP server port
  ## @param smtpUser SMTP username
  ## @param smtpPassword SMTP user password
  ## @param smtpProtocol SMTP protocol
  ##
  smtpHost: ""
  smtpPort: ""
  smtpUser: ""
  smtpPassword: ""
  smtpProtocol: ""
  ## @param smtpExistingSecret The name of an existing secret with SMTP credentials
  ## NOTE: Must contain key `smtp-password`
  ## NOTE: When it's set, the `smtpPassword` parameter is ignored
  ##
  smtpExistingSecret:



  service:
    ## @param service.type WordPress service type
    type: ClusterIP

  ingress:
    ## @param ingress.enabled Enable ingress record generation for WordPress
    ##
    enabled: true
    ## @param ingress.certManager Add the corresponding annotations for cert-manager integration
    ##
    certManager: false
    ## @param ingress.pathType Ingress path type
    ##
    pathType: ImplementationSpecific
    ## @param ingress.apiVersion Force Ingress API version (automatically detected if not set)
    ##
    apiVersion:
    ## @param ingress.hostname Default host for the ingress record
    ##
    hostname: wordpress-test.intra.vsa.de
    ## @param ingress.path Default path for the ingress record
    ## NOTE: You may need to set this to '/*' in order to use this with ALB ingress controllers
    ##
    path: /
    ## @param ingress.annotations Additional custom annotations for the ingress record
    ## NOTE: If `ingress.certManager=true`, annotation `kubernetes.io/tls-acme: "true"` will automatically be added
    ##
    annotations: {}
    ## @param ingress.tls Enable TLS configuration for the host defined at `ingress.hostname` parameter
    ## TLS certificates will be retrieved from a TLS secret with name: `{{- printf "%s-tls" .Values.ingress.hostname }}`
    ## You can:
    ##   - Use the `ingress.secrets` parameter to create this TLS secret
    ##   - Relay on cert-manager to create it by setting `ingress.certManager=true`
    ##   - Relay on Helm to create self-signed certificates by setting `ingress.tls=true` and `ingress.certManager=false`
    ##
    tls: true
    ## @param ingress.extraHosts An array with additional hostname(s) to be covered with the ingress record
    ## e.g:
    ## extraHosts:
    ##   - name: wordpress.local
    ##     path: /
    ##
    extraHosts: []
    ## @param ingress.extraPaths An array with additional arbitrary paths that may need to be added to the ingress under the main host
    ## e.g:
    ## extraPaths:
    ## - path: /*
    ##   backend:
    ##     serviceName: ssl-redirect
    ##     servicePort: use-annotation
    ##
    extraPaths: []
    ## @param ingress.extraTls TLS configuration for additional hostname(s) to be covered with this ingress record
    ## ref: https://kubernetes.io/docs/concepts/services-networking/ingress/#tls
    ## e.g:
    ## extraTls:
    ## - hosts:
    ##     - wordpress.local
    ##   secretName: wordpress.local-tls
    ##
    extraTls:
      - hosts:
          - wordpress-test.intra.vsa.de
        secretName: intra-vsa-de
    ## @param ingress.secrets Custom TLS certificates as secrets
    ## NOTE: 'key' and 'certificate' are expected in PEM format
    ## NOTE: 'name' should line up with a 'secretName' set further up
    ## If it is not set and you're using cert-manager, this is unneeded, as it will create a secret for you with valid certificates
    ## If it is not set and you're NOT using cert-manager either, self-signed certificates will be created valid for 365 days
    ## It is also possible to create and manage the certificates outside of this helm chart
    ## Please see README.md for more information
    ## e.g:
    ## secrets:
    ##   - name: wordpress.local-tls
    ##     key: |-
    ##       -----BEGIN RSA PRIVATE KEY-----
    ##       ...
    ##       -----END RSA PRIVATE KEY-----
    ##     certificate: |-
    ##       -----BEGIN CERTIFICATE-----
    ##       ...
    ##       -----END CERTIFICATE-----
    ##
    secrets: []
